### ISSUE TITLE
planning doc

### ISSUE THREAD

**Issue by tommyngre** [schmitty890/swap-shop#1]
Link to google doc where we've tried to break down the app into pages/routes/react components:
https://docs.google.com/document/d/11i4ptYfo6PzdptFObf2NnBR7dxP7vv93Ef2sLgI2giI/edit?usp=sharing

(That should be a view link, but everyone on the proj should have edit permission.)

**Comment by JoeWrightNC** [comment]
This looks good, thanks for thinking through this tommy.  If we get time I'd like to make a cool interactive react thing for when you create an account that demos how to use the community and the features too.   As far as components, I'm going to organize them by page for now just to start getting them in there.  i.e. make a directory for each page on your list one at a time and build all the components in that folder that I think we need to make each page on your list.   If we find ourselves sharing components between pages we can move them to a global folder maybe?

**Comment by tommyngre** [comment]
closing issue. we've made a lot of decisions about how to build the site offline, and have not kept up the document. it was useful for planning bu has not been used as a "working doc"
