### ISSUE TITLE
Make user model

### ISSUE THREAD

**Issue by JoeWrightNC** [schmitty890/swap-shop#15]
Look at the npm jason ws suggesting using and figure out what sort of data we get back from social logins, build user model accordingly.  Will need to have associations with message models, currency amount, perhaps rating, associations with reviews model to pull reviews they've written and ones written about them.  Comment with more things you think of.  Great thing about Mongo is we can add as we go if needed.

**Comment by JoeWrightNC** [comment]
use join form

**Comment by tommyngre** [comment]
looking at fields on the front-end, and after the discussion about review, here are fields i see:

**address object**
- street address
- city
- state

**social object**
- facebook
- twitter
- google

**firstname**

**lastname**

**questions object**
- why swapshop?
- describe yourself
- tags (array)

**reviews array**
- rating 0-10
- sentiment (?)
- body
- authorid
- authorname
- datestamp

**Comment by tommyngre** [comment]
closing issue. you can see what we settled on here: [](https://github.com/schmitty890/swap-shop/blob/master/models/User.js)
