### ISSUE TITLE
Make Postings Model

### ISSUE THREAD

**Issue by JoeWrightNC** [schmitty890/swap-shop#16]
three types, services, markets, or request.  Cost in our currency, id/rating of the person who posted it, a picture for the service (maybe using AWS) are all things we will need in the model, maybe more.

**Comment by JoeWrightNC** [comment]
sorry, I meant to say Lisitngs model to use the language on the site.

**Comment by JoeWrightNC** [comment]
poster:
name:
description:
image:
cost:

**Comment by tommyngre** [comment]
i'd also add a boolean `active` prop. if accepted or declined, it can be set to false, which could hide it. or users could re-activate it via profile/management

**Comment by tommyngre** [comment]
if we choose to incorporate messages with offers (e.g. "hi, i'd be delighted to pay you some simbis for your crap") we could have an `offers` prop which stores an array of `offer` objects with props like
- offerAuthor
- offerBody
- active

**Comment by tommyngre** [comment]
closing issue. you can see what settled on here: [](https://github.com/schmitty890/swap-shop/blob/master/models/listings.js)
