### ISSUE TITLE
transaction strategy

### ISSUE THREAD

**Issue by tommyngre** [schmitty890/swap-shop#94]
Right now we have these important attributes stores in listings:
- _id
- AuthorId (ref to user model)

We can pass those as props into a stateful `offer component` that's respresented in the `offer model`, which will only have these few 
- _id (Offer primary key/id)
- associatedListing (ref to Listing)
- associatedListingAuthor (ref to User)
- offerAuthorId (ref to User) 
- offerAuthorName
- offerMessage (optional message, e.g. "let's make this lotion for guitar lessons trade happen!")
- rate
- active (flag to display differently if the offer is pending or if accepted/declined)
- dateTime: optionally, we could format this into "9 days ago"

with all that info, we should be able to access it wherever we need to

for example, we could load offers in a dashboard section, or replace "Reviews" with "Offers" since I don't think we plan to do anything with reviews.

![image](https://user-images.githubusercontent.com/22546096/43368427-c6d93f78-932a-11e8-992d-6bc21311aea4.png)

once that's in place, i think we can make an Accept button on the offer do all the work, as far as the bart-math goes (i.e. subtract barts from offer user, add barts to listing user)

**Comment by JoeWrightNC** [comment]
this all sounds good to me Tommy.

**Comment by catchbb14** [comment]
Sounds great man, I think the best thing to do right now is run with something and if we have to change something then we will!

**Comment by tommyngre** [comment]
@JoeWrightNC @catchbb14 

👍 i got a start on all of this yesterday ([see pull request](https://github.com/schmitty890/swap-shop/pull/99))

i'll be at work till 6ish, then will work my butt of on this tonight. meanwhile, if you have an opportunity to pick up where i left off (pull request has pretty decent notes on my progress), will be much appreciated

**Comment by tommyngre** [comment]
closing issue - we ended up going more or less with this strategy.
